# Copyright 2019 Wirepas Ltd

version: '2'
services:

    # this is not recommended for production - you should have more es nodes
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1

        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

        restart: always

        ulimits:
          memlock:
            soft: -1
            hard: -1

        volumes:
          - esdata:/usr/share/elasticsearch/data

        ports:
          - 9200:9200

        logging:
          driver: json-file
          options:
            max-size: "1M"

        networks:
            - fluentd_stream_processing
            - elastic_network

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.10.0
        volumes:
            - ./kibana.yml:/usr/share/kibana/config/kibana.yml

        restart: always

        ports:
            - 5601:5601

        networks:
            - elastic_network

        logging:
            driver: json-file
            options:
                max-size: "1M"

volumes:
    esdata:
        driver: local

networks:
    elastic_network:
    fluentd_stream_processing:
      external: true
